### ISSUE TITLE
Activity Feed is empty

### ISSUE THREAD

**Issue by vpzed** [TheBLVD/mammoth#108]
**Describe the bug**
Activity pane does not load any content

**To Reproduce**
Open app, select the Bell icon to open Activity pane. Pull down to refresh Activity pane.

**Expected behavior**
Activity pane shows notification content such as likes, boosts, follows, etc.

**Screenshots**
![IMG_0013](https://github.com/TheBLVD/mammoth/assets/30138020/8949756e-e31e-4670-87b5-82d6beeef912)

**Smartphone (please complete the following information):**
 - Device: 5th generation iPad Pro 12.9
 - OS: iPadOS 16.5.1
 - Version [e.g. 22]: 1.9 build 213

**Comment by bdecrem** [comment]
I think this is a Rate Limit hit issue: when the app fires off too many network requests within a short period of time, the server will block any requests for X minutes. During that period there'll be various misbehaviors. This is more frequent on the iPad because of the app's architecture. I'm filing a ticket on this and we'll let you know when this is addressed. 

If you still have some energy for this, it would be helpful to submit a log file from Get In Touch > Submit Log File - will help us confirm that this is what's going on.

**Comment by vpzed** [comment]
I've seen it not fill Activities on startup and then it fills later, and other times where it doesn't fill even after plenty of time has passed. However, I did an uninstall/re-install and reproduced the blank Activities. This time it did fill after awhile.  See attached logs in ZIP file.

[Mammoth_Log.zip](https://github.com/TheBLVD/mammoth/files/11940659/Mammoth_Log.zip)

Note: On re-install with this new version I saw an very strange bug where on re-install I had to re-login, which I did but after clicking the Authorize button it did not proceed to the normal app screen. It just sat there with no way to proceed. Hitting Authorize again didn't help. If I backed up and tried to login again it said I was already logged-in. A force-quit and restart of the app did bring up the normal app screen. That's a new one for me, but until today I haven't done a reinstall to get you fresh logs. Weird.

**Comment by bdecrem** [comment]
thanks for the additional context and logs. we will not get to this directly in sprint 10 (next week's release) but I've update the ticket and hope we'll investigate soon. there is a decent chance that the sprint 10 work makes this better though - major changes underway in all feeds

**Comment by bvon** [comment]
This issue has been resolved (MAM-2081)
