### ISSUE TITLE
Request: allow users to choose custom fonts

### ISSUE THREAD

**Issue by dldsantos** [TheBLVD/mammoth#12]
It would be nice to have the ability to customize Mammoth’s fonts. In some cases using Open Dyslexic or Atkinson Hyperlegible, for instance, can increase a11y.

**Comment by bdecrem** [comment]
thank you!

**Comment by st3fan** [comment]
Also font size please. Should that be a separate request? Happy to file.

**Comment by pjolt** [comment]
> Also font size please. Should that be a separate request? Happy to file. 

Generally speaking it's enough if you just vote on a existing feature request or bug report by giving it a thumbs up, that lets the team know what issues might need priority. 

Also with bugs no need to fill up issues with comments like "I have this too" if a few have/can comment that they experience the issue it's enough if the rest experiencing it gives a thumbs up. 

Obviously it's up to the Mammoth team to decide how they want to handle these things. But while we wait for them to sort everything out and get routines in place etc I think we could adhere to those  suggestions mentioned until someone says otherwise. 🙂

**Comment by pjolt** [comment]
> Also font size please. Should that be a separate request? Happy to file.

In the app going to **Settings >Post appearance** has a option for **Text size** which changes the size of text. Is this what you are after or did i misunderstand your request?
