### ISSUE TITLE
Post stats disparity between Home feed and actual post

### ISSUE THREAD

**Issue by poopsicles** [TheBLVD/mammoth#140]
**Describe the bug**
When scrolling the home feed, a post might seem to have a certain number of likes, but upon opening the actual post, the number often goes up after loading other details, like the app from which it was posted.

**To Reproduce**
1. Go to your home feed.
2. Observe the like count.
3. Tap the post.
4. See the like count change.

**Expected behavior**
The like count should remain consistent across both pages.

**Screenshots**

Post in feed:
![IMG_1937](https://github.com/TheBLVD/mammoth/assets/87488715/2179b9de-51a8-45eb-b59b-30a06cc5c301)

Post in detail:
![IMG_1938](https://github.com/TheBLVD/mammoth/assets/87488715/20dce49f-bf37-488f-84f6-252143b16cbe)

Recording:
![Video](https://github.com/TheBLVD/mammoth/assets/87488715/054917fd-2883-41b6-b6fd-03f57c992ab5)

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: iOS 15.7.8 (19H364)
 - Version 2.0 (261)

**Additional context**
This is probably due to the way Mastodon is architectured maybe? Like the initial number of likes is from people in my instance and the final number is overall...but it would be nice if it there was a way to "preload" it.

**Comment by NathanRLiu** [comment]
Hey there! Thanks for submitting this. This behavior is actually intentional and a result of the way Mastodon handles these things; the timeline view shows posts as they are seen by your instance, which means that it only shows interactions from users on the same instance as you. So in this case, only 2 people from your instance have liked that post. When you go to the detail view, we ask the instance that the post originated from for the information. This means that it contains information on every user across all instances who have liked the post. But if we were to display that information on the timeline view, we would have to ask for it individually for every single post. This would result in a lot of network traffic and an increase in rate limiting issues, which is why we don't ask the post's original instance for the complete data until a user clicks into the detail view.

**Comment by poopsicles** [comment]
alright, thanks
