### ISSUE TITLE
parsing html.

### ISSUE THREAD

**Issue by derspyy** [TheBLVD/mammoth#211]
### Is your feature request related to a problem? Please describe.

the mastodon api delivers content through html. mammoth currently, to my understanding, only strips away some html tags and does a very basic parse. it would be interesting if it parsed the html entirely, to show bold, italics, code blocks, etc. which are offered by some instances and services.

### Describe the solution you'd like.

i was thinking of trying to implement it using the [SwiftSoup](https://github.com/scinfu/SwiftSoup) library, but i'm yet to see how it fits in the project's internals, and i don't know how much the mammoth team wants to rely on third-party libraries.

### Additional context.

![image](https://github.com/TheBLVD/mammoth/assets/65043391/61d6280a-0511-40ea-b55c-ffc77e96bb8a)
is displayed as follows:
![image](https://github.com/TheBLVD/mammoth/assets/65043391/37411919-61ae-4f2d-9d17-a921e1c72cce)

**Comment by derspyy** [comment]
would solve #145

**Comment by derspyy** [comment]
important links:

https://docs.joinmastodon.org/api/guidelines/#formatting

https://docs.joinmastodon.org/spec/activitypub/#sanitization

not every html element is used so using a library is very overkill. 

though the elements listed should be covered in a basic parser, with special thought given to the ones that are displayed differently (code, bold, italics, etc...) and how the parsing affects performance.

**Comment by ringmaster** [comment]
A properly working parser/sanitizer for HTML is a hard thing to build.  It should be easier to incorporate an existing, well-tested library with a whitelist than rolling something custom.  And then Mammoth would benefit from updates to that configurable library rather than having to update Mammoth code itself to fix bugs or adjust to changes in the ActivityPub spec.

Some practical thoughts here: https://blog.codinghorror.com/parsing-html-the-cthulhu-way/

Some questionable regex HTML parsing occurs in Mammoth code here: https://github.com/TheBLVD/mammoth/blob/02eef1b7558b261e3d2f7f42753ce5f5b6008e65/Mammoth/Models/GlobalStruct.swift#L339

**Comment by derspyy** [comment]
well! due on 2.4
