### ISSUE TITLE
Make the website GDPR-compatible

### ISSUE THREAD

**Issue by nemobis** [TheBLVD/mammoth#35]
**Describe the bug**
The website currently violates the GDPR. Among other things, the [current version](https://web.archive.org/web/20230226022833/https://getmammoth.app/details.html) loads resources from Google LLC and links a [privacy policy page](https://web.archive.org/web/20230226022925/https://melted-april-eb6.notion.site/Privacy-Policy-4ab2497fe2f44220a8189dcd84de4327) controlled by The BLVD, Inc. and hosted by Notion Labs, Inc. on Amazon Technologies Inc. machines and fronted by Cloudflare, Inc. (currently 2606:4700:4400::ac40:9a18 for me). Despite transferring personal data of all visitors to no less than 5 USA corporations, the privacy policy falsely states that

> We do not [...] transfer to outside parties your personally identifiable information.

**Expected behavior**
The website should comply with GDPR. At a minimum, the privacy policy should not contain false statements.

*I release this comment under CC-0, MPL2 and AGPLv3*.

**Comment by ShihabM** [comment]
Thanks for this!

**Comment by Krinkle** [comment]
@bvon It appears this issue was not resolved.

The privacy policy still incorrectly states that no personal information is transferred to third-parties. It appears the privacy policy is now actually a copy of an another website's privacy policy, including a very strange description in the first paragraph which suggests that this is not Mammoth's policy but rather mastodon.social's policy.

> This privacy policy describes how **mastodon.social ("mastodon.social", "we", "us")** collects […] information you may provide through the **mastodon.social website or its API**.

The https://getmammoth.app/ home page still loads CSS from fonts.googleapis.com. Consider self-hosting this or acknowledging this third-party dependency, which is given full access to the user's IP, browser/device details, and approximate active geo location and time of day, as well as Referer information about the person's interest in Mammoth.

Since this issue was created, the home page gained a second third-party dependency on jsdelivr.net, which sends the same information to Cloudflare and Fastly. Similarly to the font, this resouce would be easy to self-host within Netlify, but otherwise probably needs to be acknowledging as third-party.

**Comment by bvon** [comment]
> @bvon It appears this issue was not resolved.
> 
> 
> 
> The privacy policy still incorrectly states that no personal information is transferred to third-parties. It appears the privacy policy is now actually a copy of an another website's privacy policy, including a very strange description in the first paragraph which suggests that this is not Mammoth's policy but rather mastodon.social's policy.
> 
> 
> 
> > This privacy policy describes how **mastodon.social ("mastodon.social", "we", "us")** collects […] information you may provide through the **mastodon.social website or its API**.
> 
> 
> 
> The https://getmammoth.app/ home page still loads CSS from fonts.googleapis.com. Consider self-hosting this or acknowledging this third-party dependency, which is given full access to the user's IP, browser/device details, and approximate active geo location and time of day, as well as Referer information about the person's interest in Mammoth.
> 
> 
> 
> Since this issue was created, the home page gained a second third-party dependency on jsdelivr.net, which sends the same information to Cloudflare and Fastly. Similarly to the font, this resouce would be easy to self-host within Netlify, but otherwise probably needs to be acknowledging as third-party.

I'll pass this on to the team so they can address this accordingly. Thanks!

**Comment by bdecrem** [comment]
hi guys, I'll try to have this addressed for the mammoth 2 launch. thanks for re-flagging.

**Comment by bvon** [comment]
Spoke with @jtomchak, and it looks like we are GDPR compliant :)
