### ISSUE TITLE
Scrolling through images

### ISSUE THREAD

**Issue by jaslowry** [TheBLVD/mammoth#53]
**Describe the bug**
When scrolling through images, the count will sometimes go back to 1 (sometimes the image preview will go back to the first image, other times it will show the second image).

**To Reproduce**
1. Find a post with more than one image
2. Scroll to the second image. Note the count goes back to 1.

**Expected behavior**
The count should show the correct image number after scrolling.

**Screenshots**

https://user-images.githubusercontent.com/126299992/223411070-4ccda9d7-2bc5-41e8-80f1-07424f0571fd.mov

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.4 beta 2
 - Version 1.1 build 119

**Additional context**

**Comment by NathanRLiu** [comment]
Hi Jason,
I was unable to reproduce this bug. If you have the time, would you mind confirming that this is still an issue? Although I wasn't able to reproduce this particular bug, I found two similar issues. The first issue is that if you scroll halfway past the a post with a carousel that you swiped through, the carousel will revert to the original slide. The second similar issue I found while attempting to reproduce this bug is that if you open the picture in fullscreen, swipe through it, and then exit the picture focus view, it will revert back to the original slide as well. I've submitted these two issues to Mammoth's internal issue tracker.

Despite being able to reproduce those two issues, I wasn't able to reproduce the issue you demonstrated in your screen recording and I'm not sure if that's because it's been resolved or because I'm not following the steps correctly. I would encourage you to try and test your original issue and see if it still occurs, and if it does let me know and I'll spend some more time trying to reproduce it myself.

Thank you for submitting this report!

**Comment by bvon** [comment]
LGTM in version 2.
